---
title: "New studies support blood test for early detection of Alzheimer’s disease."
description: |
  Fifth article found on ScienceDaily
author:
  - name: Buket Duran
date: 03-15-2021
categories: 
  - "English for Science"
#preview:
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
# Source of the article with publication date and word count :  
Source of the article: 
https://www.sciencedaily.com/releases/2021/01/210113100824.htm ( 13 January 2021) 
 
Word count : 748 

# Vocabulary :  
| Word from the text    | Synonym/definition in English     | French translation     |
|-----------------------|-----------------------------------|------------------------|
| convincing            | powerful                          | Convaincant            |
| The early detection   |  Means a disease detection        | La détection précoce   |
| underlying            | /                                 | Sous-jacent            |
| inasive               | Which can alternate the organism  | inasif                 |
| affordable            | cheap                             | abordable              |

# Analysis table about the study

| Researchers ?                      | University of Gothenburg                                                                                                                                                                                                                             |
|------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Published in ? When (if mentioned) | 13 January 2021                                                                                                                                                                                                                                      |
| General topic                      | Researchers provide convincing evidence that an in-house developed blood test for Alzheimer's disease can detect the disease early and track its course, which has major implications for a potential use in clinical practice and treatment trials. |
| Study and Conclusion               | In conclusion the blood test to detect Alzheimer’s disease should be updated for everyone around the world, to limit the acceleration of the disease.                                                                                                |
