---
title: "My English Activity Log : MEAL"
author:
  - name: "Buket Duran" 
date: "`r Sys.Date()`"
categories:
  - "English for Science"
  - "M.E.A.L."
  - "nouvelle catégorie"
output: distill::distill_article
---

# MEAL

It might be late right now but I wasn't sure what I should put in this part of the blog 
I think I have to present a little my year.

- Sept. 25th: I downloaded the "BBC News" App on my phone. I have started reading/watching the news in my bed. 

- Sept. 28th: I went to university for my second course.

- Oct 10th: I tried to watch a movie with the English subtitles. It was a real desaster because I couldn't read and watch the movie at the same time.

- Oct 15th: I decided to listen to more English music so I spent the day singing with my beautiful accent.

- Oct 25th: We watched a series in English with my boyfriend. According to him it was a way to improve even more in English, he had fun asking me questions to know if I had understood correctly.

- Oct 27th: I started to watch this series by myself, it was not easy at first but with time I managed to adapt.

- Nov 1th: I decided to change my device language into English. Now my computer is configured in English. 

It's not going to be easy but it's important to learn the language especially English that passes everywhere. 

-


